# Generated by Django 5.0.7 on 2024-08-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_flower_alter_flower_name_orderflower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flowers',
        ),
        migrations.AddField(
            model_name='order',
            name='flower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.flower'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.DeleteModel(
            name='OrderFlower',
        ),
    ]
