# Generated by Django 5.0.7 on 2024-08-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_order_flower_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flowers',
            field=models.ManyToManyField(through='main.OrderFlower', to='main.flower'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость заказа'),
        ),
        migrations.AlterField(
            model_name='orderflower',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
