# Generated by Django 5.0.7 on 2024-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_flowers_order_flower_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='password', max_length=255, verbose_name='Пароль'),
        ),
    ]
